[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"

[browser]
gatherUsageStats = false

[ui]
showSidebarNavigation = true
hideTopBar = true
showThemeSelector = false
